services:
  app:
    # image: thevickypedia/vaultapi
    container_name: vaultapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    ports:
      # host_port:container_port
      - "9010:8080"
    deploy:
      # 'reservations' key is supported only in swarm mode
      resources:
        limits:
          cpus: '1'
          memory: 200M
