import hashlib
import hmac
import logging
import time

LOGGER = logging.getLogger("uvicorn.default")


def generate(token: str) -> str:
    """Generate an authentication header value for API requests.

    Args:
        token: Shared API token used as the HMAC secret key.

    See Also:
        - The generated header contains:
            - A Unix timestamp in seconds.
            - An HMAC-SHA512 signature computed using the API token as the secret key and the timestamp as the message.
        - | The server can validate the signature and ensure the timestamp is within an acceptable age window,
          | to reduce replay attacks.

    Example:
        Authorization: Signature=<signature>,timestamp=<timestamp>

    Returns:
        str:
        Authentication header value containing the signature and timestamp.
    """
    timestamp = str(int(time.time()))
    signature = hmac.new(
        token.encode("utf-8"),
        timestamp.encode("utf-8"),
        hashlib.sha512,
    ).hexdigest()
    return f"Signature={signature},timestamp={timestamp}"


def validate(auth_header: str, token: str, validity: int) -> bool:
    """Validate an authentication header generated by ``generate``.

    See Also:
        1. Parses the signature and timestamp from the header.
        2. Verifies the timestamp is not expired.
        3. Rejects timestamps that are excessively far in the future.
        4. Recomputes the expected HMAC-SHA512 signature.
        5. Compares signatures using a constant-time comparison.

    The function assumes requests are transmitted over HTTPS. Without
    TLS, an attacker could intercept and replay valid authentication
    headers during the accepted timestamp window.

    Accepted header format:
        Signature=<signature>,timestamp=<timestamp>

    Args:
        auth_header: Raw authentication header value received from the client.
        token: Shared API token used as the HMAC secret key.
        validity: Valid bearer token expiration time in seconds.

    Returns:
        True if the header is valid and the signature matches, otherwise False.
    """
    try:
        parts = {}
        for item in auth_header.split(","):
            key, value = item.strip().split("=", 1)
            parts[key] = value
        signature = parts["Signature"]
        timestamp = parts["timestamp"]
        ts = int(timestamp)
    except Exception as exc:
        LOGGER.warning("Invalid auth header: %s", exc)
        return False

    now = int(time.time())

    # Allow a small amount of clock skew tolerance between systems
    clock_skew_tolerance = round(validity / 5)
    if ts > now + clock_skew_tolerance:
        LOGGER.warning("Timestamp too far in the future - invalid")
        return False

    # Reject stale requests (symmetric skew tolerance: same grace applies in both directions)
    if now - ts > validity + clock_skew_tolerance:
        LOGGER.warning("Timestamp too far in the past - invalid")
        return False

    expected = hmac.new(
        token.encode("utf-8"),
        timestamp.encode("utf-8"),
        hashlib.sha512,
    ).hexdigest()

    if hmac.compare_digest(signature, expected):
        LOGGER.debug("Valid bearer token")
        return True
    LOGGER.warning("Invalid bearer token")
    return False


if __name__ == "__main__":
    TOKEN = "{apikey}.{secret}"
    _validity = 5
    header = generate(TOKEN)
    time.sleep(5)  # Simulate delay to test expiration
    assert validate(header, TOKEN, _validity) is True
    header = generate(TOKEN)
    time.sleep(6)  # Simulate delay to test expiration
    assert validate(header, TOKEN, _validity) is False
