"""Header module that generates and validates HMAC-SHA512 signed authentication headers."""

import hashlib
import hmac
import logging
import time

LOGGER = logging.getLogger("uvicorn.default")


def generate(token: str) -> str:
    """Generate an HMAC-SHA512 signed authentication header value.

    The header encodes a Unix timestamp and a signature so the server can
    verify both the token and the request's age, reducing replay attack risk.

    See Also:
        Header format: ``Signature=<hex_digest>,timestamp=<unix_seconds>``

    Args:
        token: Shared API token used as the HMAC secret key.

    Returns:
        str:
        Authentication header value containing the signature and timestamp.
    """
    timestamp = str(int(time.time()))
    signature = hmac.new(
        token.encode("utf-8"),
        timestamp.encode("utf-8"),
        hashlib.sha512,
    ).hexdigest()
    return f"Signature={signature},timestamp={timestamp}"


def validate(auth_header: str, token: str, validity: int) -> bool:
    """Validate an authentication header generated by ``generate``.

    See Also:
        Validation steps:
        1. Parse the signature and timestamp from the header.
        2. Reject timestamps too far in the future (clock skew tolerance = ``validity // 5``).
        3. Reject timestamps that have expired beyond the validity window.
        4. Recompute the expected HMAC-SHA512 signature.
        5. Compare signatures with a constant-time digest to prevent timing attacks.

    Args:
        auth_header: Raw authentication header value received from the client.
        token: Shared API token used as the HMAC secret key.
        validity: Accepted age of the header in seconds.

    Returns:
        bool:
        ``True`` if the header is structurally valid, unexpired, and the signature
        matches; ``False`` otherwise.
    """
    try:
        parts = {}
        for item in auth_header.split(","):
            key, value = item.strip().split("=", 1)
            parts[key] = value
        signature = parts["Signature"]
        timestamp = parts["timestamp"]
        ts = int(timestamp)
    except Exception as exc:
        LOGGER.warning("Invalid auth header: %s", exc)
        return False

    now = int(time.time())

    # Allow a small amount of clock skew tolerance between systems
    clock_skew_tolerance = round(validity / 5)
    if ts > now + clock_skew_tolerance:
        LOGGER.warning("Timestamp too far in the future - invalid")
        return False

    # Reject stale requests (symmetric skew tolerance: same grace applies in both directions)
    if now - ts > validity + clock_skew_tolerance:
        LOGGER.warning("Timestamp too far in the past - invalid")
        return False

    expected = hmac.new(
        token.encode("utf-8"),
        timestamp.encode("utf-8"),
        hashlib.sha512,
    ).hexdigest()

    if hmac.compare_digest(signature, expected):
        LOGGER.debug("Valid bearer token")
        return True
    LOGGER.warning("Invalid bearer token")
    return False


if __name__ == "__main__":
    TOKEN = "{apikey}.{secret}"
    _validity = 5
    header = generate(TOKEN)
    time.sleep(5)  # Simulate delay to test expiration
    assert validate(header, TOKEN, _validity) is True
    header = generate(TOKEN)
    time.sleep(6)  # Simulate delay to test expiration
    assert validate(header, TOKEN, _validity) is False
