import binascii
import hashlib
import hmac
import logging
import operator
import os
import time
from typing import Callable

LOGGER = logging.getLogger("uvicorn.default")

# Persists a timestamp for the given # of seconds
LATENCY_TOLERANCE = 5
# Clock skew tolerance for a timestamp in seconds
SKEW_TOLERANCE = 1


def _apply_op(a: int, b: int, op: Callable) -> int:
    """Applies an arithmetic operation between two integers."""
    return op(a, b)


def authorization(token: str, skew: int = 0, operation: Callable = operator.add):
    """Prepares the authorization header.

    Args:
        token: Input string to be signed.
        skew: Clock skew tolerance in seconds.
        operation: Operation to apply to the timestamp and skew (default is addition).

    Returns:
        str:
        Returns the input string with a timestamp attached at the end.
    """
    timestamp = int(time.time() // LATENCY_TOLERANCE)
    skewed = _apply_op(timestamp, skew, operation)
    return f"{token}.{skewed}"


def generate_signed_token(value: str) -> str:
    """Generates a signed token for a given value.

    Args:
        value:

    Security:
        - PBKDF2 hashes value.encode('utf-8') (bytes)
        - Uses a random 16-byte salt (os.urandom(16)), so the same input produces a different output each time
        - Runs 100,000 iterations, intentionally slow to resist guessing attacks.

    Returns:
        str:
        Returns hex(salt + derived_key) (salt prepended to hash) as a hex string.
    """
    salt = os.urandom(16)
    pw_hash = hashlib.pbkdf2_hmac('sha256', value.encode('utf-8'), salt, 100_000)
    # Combine salt and hash, then convert to hex string
    return binascii.hexlify(salt + pw_hash).decode('utf-8')


def verify_signed_token(
        received_hash: str,
        candidate_token: str,
) -> bool:
    """Verifies a signed token for a given candidate token.

    Args:
        received_hash: Hash received from the client.
        candidate_token: Token generated by the server.

    Returns:
        bool:
        Returns True if the token is valid, False otherwise.
    """
    try:
        stored_bytes = binascii.unhexlify(received_hash)
    except binascii.Error as error:
        LOGGER.error(error)
        return False
    salt = stored_bytes[:16]
    stored_hash = stored_bytes[16:]
    pw_hash = hashlib.pbkdf2_hmac('sha256', candidate_token.encode('utf-8'), salt, 100_000)
    return hmac.compare_digest(stored_hash, pw_hash)


def generate(token: str) -> str:
    """Generates a timestamp based token for a given input string.

    Args:
        token: Input string to be signed.

    Returns:
        str:
        Signed token.
    """
    prepared = authorization(token)
    return generate_signed_token(prepared)


def verify(*args, received_hex: str) -> bool:
    """Generates a timestamp based token for a given input string and verifies it against a received hash.

    Args:
        token: Input string to be verified.
        received_hex: Received hex string.

    See Also:
        - Generates an absolute token for the timestamp.
        - Adds a clock skew tolerance in case absolute match fails.

    Examples:
        If the first call happens near the end of a 5-second bucket, the second call can be in the next bucket.

        .. code-block:: python

            t = 14.9s #  -> int(14.9 // 5) = 2
            sleep(3)  # Simulating network latency
            t = 17.9s # -> int(17.9 // 5) = 3

    Returns:
        bool:
        Returns True if the token is valid, False otherwise.
    """
    token = ".".join(args)
    canonical_token = authorization(token)
    # Allows 1s in the past for clock skew tolerance
    skew_tolerant_token = authorization(token, skew=SKEW_TOLERANCE, operation=operator.sub)
    return (
            verify_signed_token(received_hex, canonical_token) or
            verify_signed_token(received_hex, skew_tolerant_token)
    )
